name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      - name: docker:dind

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan -t rsa -H ${{ secrets.IP_ADDRESS }} >> ~/.ssh/known_hosts

      - name: Build and deploy
        run: |
          rm -rf .git*
          ssh -vvv -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@${{ secrets.IP_ADDRESS }} "mkdir -p /tmp/app"
          tar -czf - . | ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@${{ secrets.IP_ADDRESS }} "tar -xzf - -C /tmp/app; mkdir -p /home/root/nodeapp"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@${{ secrets.IP_ADDRESS }} "rm -rf /home/root/nodeapp/* ; rm -rf /home/root/nodeapp/.* ; cp -r /tmp/app/. /home/root/nodeapp/ ; rm -rf /tmp/app"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@${{ secrets.IP_ADDRESS }} "cd /home/root/nodeapp/ && sudo docker-compose -f docker-compose.yml up --build --force-recreate -d"
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
