# name: Deploy to Remote Server

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up SSH
#       uses: webfactory/ssh-agent@v0.5.0
#       with:
#         ssh-private-key: ${{ secrets.PRIVATE_KEY }}

#     - name: SSH into remote server
#       run: |
#         ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.IP_ADDRESS }} "mkdir -p /tmp/app/app2/app3"


# name: Run Example Job

# on:
#   push:
#     branches:
#       - main

# jobs:
#   run_example_job:
#     runs-on: ubuntu-latest
#     timeout-minutes: 5

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Print out Example Job
#         uses: appleboy/ssh-action@v0.1.10
#         with:
#           host: ${{ secrets.IP_ADDRESS }}
#           username: ${{ secrets.SSH_USER }}
#           key: ${{ secrets.PRIVATE_KEY }}
#           port: ${{ secrets.SSH_PORT }}
#           command_timeout: 30m
#           script: |
#             mkdir -p /tmp/app/
#             tar -czf - . "tar -xzf - -C /tmp/app; mkdir -p /home/root/nodeapp"


name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 400 private_key.pem

      - name: Build and deploy
        run: |
          ssh -vvv -o StrictHostKeyChecking=no -i private_key.pem root@147.182.198.18 "mkdir -p /tmp/app/"
          tar -czf - . | ssh -o StrictHostKeyChecking=no -i private_key.pem root@147.182.198.18 "tar -xzf - -C /tmp/app/; mkdir -p /home/root/dictionary"
          ssh -o StrictHostKeyChecking=no -i private_key.pem root@147.182.198.18 "rm -rf /home/root/dictionary/* ; rm -rf /home/root/dictionary/.* ; cp -r /tmp/app/. /home/root/dictionary/ ; rm -rf /tmp/app"
          ssh -o StrictHostKeyChecking=no -i private_key.pem root@147.182.198.18 "cd /home/root/dictionary/ && sudo docker build --no-cache -t dictionary ."
     
      - name: Clear Repo and codes
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem root@147.182.198.18 " rm -rf /home/root/dictionary/*"

    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

#abc